// corpus para medir falsos positivos del detector: palabras muy comunes de las letras (español e inglés)
// y frases neutras. Lo que dispara de forma legítima va en PERMITIDOS (palabra -> ids aceptados).
export const PALABRAS = `i you he she we they me my your his her our it is are was were be been am do does did have has had will would can could just like love baby girl boy man woman night day time life world heart eyes hands head face body mind soul feel know think want need see look go come get give take make say tell call run walk stay leave fall fly dance sing cry smile laugh hold touch kiss burn fire water rain sun moon star sky sea light dark black white red blue green gold money cash car road street city home house door room bed floor wall window down up out in on off over under again still never always ever now then here there where when why how what who all one two three more most some any every no not yes oh yeah hey ooh mama papa mom dad friend brother sister god devil angel dream sleep wake morning tonight tomorrow yesterday right left back front side top bottom high low big small old new young good bad nice sweet hot cold long short hard soft fast slow free lost found alone together cause because though maybe better best last first next same other own real true fake crazy lonely broken empty full open close the a an and or but so if as at by for from of to with without about around through between into against before after during while since until shit fuck damn bitch nigga yo uh ah wanna gonna gotta
de la que el en y a los se del las por un para con no una su al lo como mas pero sus le ya o este si porque esta entre cuando muy sin sobre tambien me hasta hay donde quien desde todo nos todos uno les ni contra otros ese eso ante ellos esto antes algunos unos yo otro otra tanto esa estos mucho nada poco ella estar estas algo nosotros mi mis tu te ti tus ellas amor vida noche dia tiempo mundo corazon ojos manos cabeza cara cuerpo mente alma siento pienso quiero necesito veo miro voy vengo doy tomo hago digo llamo corro camino quedo dejo caigo vuelo bailo canto lloro sonrio rio sostengo toco beso quemo fuego agua lluvia sol luna estrella cielo mar luz oscuro negro blanco rojo azul verde oro dinero carro calle ciudad casa puerta cuarto cama piso pared ventana abajo arriba fuera dentro bajo vez aun nunca siempre ahora entonces aqui alli dos tres oye mama papa amigo hermano hermana dios diablo angel sueno duermo despierto manana hoy ayer derecha izquierda atras frente lado alto grande pequeno viejo nuevo joven bueno malo dulce caliente frio largo corto duro suave rapido lento libre perdido solo juntos aunque quizas mejor ultimo primero mismo real verdadero falso loco roto vacio lleno abierto cerrado
pa vamos vas va ven tengo tienes tiene sabes sabe puedo puedes hacer hacemos dime dame mira miras pasa paso pasar pasado llega llegar llegaste vienes vino fue fui ser soy eres es somos son estoy estamos estan mami papi nena nene chico chica hombre mujer gente toda cosa cosas forma modo lugar parte caso punto momento segundo minuto hora semana mes ano anos siglo verdad mentira miedo dolor pena razon sentido idea historia palabra nombre voz ruido silencio sonido musica cancion letra ritmo beat flow rap verso
people thing things way place part case point moment second minute hour week month year years century truth lie fear pain reason sense idea story word name voice noise silence sound music song lyric rhythm verse wild forever away
pan pie mano ojo boca nariz oreja pelo piel sangre hueso mama mamá papá tío tía primo abuela abuelo hijo hija niño niña bebe novia novio esposa esposo jefe rey reina senor senora
red blue pink purple orange yellow gray grey brown silver color colors colour paint ink page book letter paper pen pencil table chair glass cup bottle plate fork knife spoon bag box ring chain key lock gun knife sword shield bullet bomb war peace fight kill dead die death alive born birth age old
hit kick push pull throw catch break fix cut drop pick lift carry bring send write read speak talk listen hear watch wait try start stop begin end finish keep let put set turn move change grow show hide seek find lose win lose play work sell buy pay owe lend borrow steal share trust lie cheat forgive forget remember miss regret
hablo hablas habla escucho oigo escribo leo pienso creo espero busco encuentro pierdo gano juego trabajo vendo compro pago robo comparto confio miento perdono olvido recuerdo extrano lamento
ayer hoy manana tarde temprano luego despues antes durante mientras hasta desde cerca lejos aqui alla arriba abajo adelante atras dentro fuera encima debajo junto contra segun sobre tras`.split(/\s+/).filter(Boolean);
// palabra -> ids que pueden dispararse con ella sin ser un error (conceptos que el dibujo representa de verdad)
export const PERMITIDOS = {
  water: ['agua'], agua: ['agua'], kiss: ['beso', 'labios'], beso: ['beso', 'labios'], sing: ['boca_canta'], canto: ['boca_canta'], voz: ['boca_canta'], voice: ['boca_canta'],
  free: ['cadena_rota', 'libertad'], libre: ['cadena_rota', 'libertad'], bed: ['cama'], cama: ['cama'], camino: ['camino'], mind: ['cerebro'], mente: ['cerebro'],
  wall: ['ladrillos'], pared: ['ladrillos'], hands: ['manos_tocan'], manos: ['manos_tocan'], mano: ['manos_tocan'], fear: ['miedo'], miedo: ['miedo'],
  ritmo: ['notas'], beat: ['notas'], rhythm: ['notas'], sleep: ['ojos_dormidos'], door: ['puerta'], puerta: ['puerta'], rio: ['rio'], street: ['semaforo_mano'], calle: ['semaforo_mano'],
  alone: ['soledad'], lonely: ['soledad'], smile: ['sonrisa'], laugh: ['sonrisa'], vacio: ['vacio'], window: ['ventana'], ventana: ['ventana'],
  // sustantivos que el catálogo dibuja a propósito: decir «mesa» o «book» saca una mesa o un libro
  pan: ['pan'], pie: ['pie_descalzo'], boca: ['labios'], oreja: ['oreja'], pelo: ['pelo', 'cabello_largo'], sangre: ['gota_sangre'], hueso: ['esqueleto', 'hueso'],
  novia: ['ramo_novia'], novio: ['ramo_novia'], reina: ['corona'], orange: ['naranja'], paint: ['pincel'], page: ['libro'], book: ['libro'], letter: ['carta'],
  pen: ['lapiz'], pencil: ['lapiz'], table: ['mesa'], chair: ['silla'], cup: ['taza'], bottle: ['botella'], plate: ['plato'], fork: ['cubiertos'], knife: ['cubiertos'],
  spoon: ['cubiertos'], bag: ['maleta'], ring: ['anillo'], chain: ['cadena'], key: ['llave'], sword: ['espada'], shield: ['escudo'], peace: ['paz'], win: ['trofeo'],
  forget: ['olvido'], regret: ['culpa'], olvido: ['olvido'], adelante: ['puerta_abierta'],
};
// frases neutras: ninguna debe dibujar nada
export const NEUTRAS = [
  'hurts like a broken promise', 'it feels like nothing is enough', 'i think about you all the time', 'he said he would come back', 'qué pena me da verte así',
  'él vino sin avisar y se fue', 'mi papá siempre me decía que no', 'no sé qué hacer con todo esto', 'sobre todas las cosas te elegí', 'todo el día pensando en ti',
  'i won\'t let you go', 'i can\'t stop now', 'you don\'t know what you\'ve got', 'i bet you didn\'t think i\'d say it', 'my boo is coming over', 'we were young and we were wild',
  'and i can\'t help it if i fall', 'pero no me importa lo que digan', 'quiero decirte que te extraño', 'lo que pasó, pasó', 'tengo que contarte algo importante',
  'nothing lasts forever', 'all i ever wanted was you', 'hay cosas que no se pueden explicar', 'cuando te vas todo cambia', 'maybe we should talk about it',
  'una y otra vez lo mismo', 'where did we go wrong', 'tal vez mañana sea diferente', 'this is how it goes', 'por eso me quedo contigo',
];
