// frases de la batería de detección, compartidas por la prueba con navegador y la de node
// [frase, id esperado] (el id esperado debe estar entre los detectados)
export const DEBE = [
  ['soy de Nicaragua, mi tierra es de volcanes', 'flag_ni'], ['los nicas somos así', 'flag_ni'], ['boricua hasta la muerte', 'flag_pr'], ['soy de Colombia', 'flag_co'],
  ['viva México cabrones', 'flag_mx'], ['I love New York', 'flag_us'], ['dancing in Paris tonight', 'flag_fr'], ['una noche en Madrid', 'flag_es'], ['direction to Tokyo', 'flag_jp'],
  ['vamos a Cuba', 'flag_cu'], ['la selección de Argentina', 'flag_ar'], ['carnaval en Brasil', 'flag_br'], ['London calling', 'flag_gb'], ['Jamaica me llama', 'flag_jm'],
  ['dominicana mi tierra', 'flag_do'], ['nos vemos en Berlín', 'flag_de'], ['from Canada with love', 'flag_ca'], ['Grecia en verano', 'flag_gr'], ['Rusia y Ucrania', 'flag_ru'],
  ['me siento tan solitario y triste', 'soledad'], ['tengo miedo de perderte', 'miedo'], ['la ira me consume', 'ira'], ['celos de todo lo que miras', 'celos'], ['no puedo dejar de pensar en ti, obsesión', 'obsesion'],
  ['una pizza y una cerveza', 'pizza'], ['me como un helado contigo', 'helado'], ['tomando vino tinto', 'vino'], ['fresas con crema', 'fresa'], ['pastel de cumpleaños', 'pastel'],
  ['mi perro me espera en casa', 'perro'], ['un gato en el tejado', 'gato'], ['como una mariposa en primavera', 'mariposa'], ['un tiburón en el mar', 'tiburon'], ['el búho de la noche', 'buho'],
  ['una estrella en el volcán', 'volcan'], ['después de la tormenta un arcoíris', 'arcoiris'], ['el amanecer en la playa', 'amanecer'], ['el planeta rojo', 'planeta'],
  ['viajando en tren de noche', 'tren'], ['un avión al cielo', 'avion'], ['despegó el cohete', 'cohete'], ['en la moto a mil', 'moto'],
  ['mi laptop y mi celular', 'laptop'], ['te mando un mensaje', 'chat'], ['tocando la guitarra', 'guitarra_acustica'], ['el saxofón suena', 'saxofon'], ['un vinilo en el tocadiscos', 'vinilo'],
  ['como Messi en la cancha', 'messi'], ['bailando como Michael Jackson', 'michael_jackson'], ['Bad Bunny en el radio', 'bad_bunny'], ['leí a Rubén Darío', 'ruben_dario'], ['Frida y sus flores', 'frida_kahlo'], ['un genio como Einstein', 'einstein'],
  ['el médico me dijo', 'medico'], ['soy bombero', 'bombero'], ['un mago en el circo', 'mago'], ['metió un gol en la portería', 'porteria'],
  ['una fiesta hasta el amanecer', 'serpentina'], ['con globos y confeti', 'globos'], ['me puse mi vestido', 'vestido'], ['tus tacones en el piso', 'tacones'], ['un abrazo eterno', 'abrazo'], ['sonrisa bonita', 'sonrisa'],
  ['bajo la torre Eiffel', 'torre_eiffel'], ['las pirámides de Egipto', 'piramides'], ['un canguro en Australia', 'canguro'], ['el cóndor de los Andes', 'condor'], ['vamos a Machu Picchu', 'machu_picchu'],
];
// frases neutras que no deben disparar ningún dibujo
export const NO = ['te quiero mucho mi amor', 'the city lights are burning', 'un café en la mañana', 'i miss you baby', 'dance until the morning sun', 'tengo el corazón roto', 'no me digas que no', 'cruzando el puente hacia tu casa', 'solo quiero estar contigo', 'tal vez mañana te vea', 'gracias por todo', 'eres mi mate en este juego', 'siempre te veo igual', 'lo que siento es real', 'quiero verte otra vez', 'tú y yo, nada más', 'eres fuerte y valiente', 'me duele el alma', 'voy paso a paso'];
// errores reales encontrados con letras de verdad: [frase, ids que NO deben salir, ids que SÍ deben salir]
export const REGRESIONES = [
  ['and it hurts like a broken heart', ['pulgar_arriba', 'redes_like'], []],
  ['me gusta tu forma de bailar', [], ['pulgar_arriba']],
  ['look at the window', ['trofeo'], ['ventana']],
  ['a glass of wine tonight', ['trofeo'], ['vino']],
  ['the wind and the winter', ['trofeo'], []],
  ['we win tonight', [], ['trofeo']],
  ['i won\'t let go', ['trofeo'], []],
  ['un pan caliente', ['ventana'], ['pan']],
  ['mi papá y mi mamá', ['papa'], []],
  ['unas papas fritas', [], ['papa']],
  ['él vino ayer', ['vino'], []],
  ['una copa de vino tinto', [], ['vino']],
  ['qué pena me da', ['roca'], []],
  ['una peña enorme', [], ['roca']],
  ['sobre todas las cosas', ['sobre'], []],
  ['todo el día pensando', ['calendario'], []],
  ['i think about you', ['cerebro'], []],
  ['the beat goes on', ['corazon_anat'], []],
  ['in short, it was nothing', ['pantalon'], []],
  ['wearing shorts', [], ['pantalon']],
  ['my boo is coming over', ['fantasma'], []],
  ['i bet you know', ['dados'], []],
  ['don\'t stop now', ['semaforo'], []],
  ['i can\'t find you', ['lupa'], []],
  ['watch me move', ['reloj_pulsera'], []],
  ['ay bebé, bebé', ['cuna'], []],
  ['no me acuerdo de nada, recuerdo poco', ['nostalgia'], []],
  ['a bright idea', [], ['bombilla']],
  ['tengo una idea', ['bombilla'], []],
  ['chocolate cookies', ['chef'], ['galleta']],
  ['i cook every night', [], ['chef']],
];
